on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
name: Test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -coverprofile=cover.out -v ./...
    - name: Report results to DeepSource
      run: |
        go test -coverprofile=cover.out

        curl https://deepsource.io/cli | sh

        ./bin/deepsource report --analyzer test-coverage --key go --value-file ./cover.out

      env:
        DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
    - name: Dynamic Badges
      uses: Schneegans/dynamic-badges-action@v1.4.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: e4a57dc55a753b929013713838d58b6e
        filename: test.json
        label: Hello
        message: World
        color: orange
